name: deep_local_storage
description: "A powerful Flutter local storage library that provides secure and persistent data storage across platforms, with support for various data types and device-level persistence."
version: 1.0.1
homepage: https://github.com/ke112
repository: https://github.com/ke112/deep_local_storage
issue_tracker: https://github.com/ke112/deep_local_storage/issues
topics:
  - storage
  - cache
  - persistence
  - local-storage
  - flutter

environment:
  sdk: ^3.4.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  rcache_flutter: ^1.1.3
  uuid: ^4.2.1
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
